<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.majestic-escape.com/</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/about</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/partners</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/blogs</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/features</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/host/property</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/host/experience</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/host/guide</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/guides</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/safety</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/privacy</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/terms</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/cancellation</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/trust-safety</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/cookies</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/faq</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/help</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/complaints</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.majestic-escape.com/contact</loc>
    <lastmod>2023-11-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>